# Generated by Django 4.2.11 on 2024-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_patient_last_treatment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='created_at',
            new_name='createTime',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='avatar',
        ),
        migrations.AddField(
            model_name='patient',
            name='Picture_avatar',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='patient',
            name='eyeN_result',
            field=models.JSONField(default=dict),
        ),
    ]
