# Generated by Django 4.2.11 on 2024-03-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_created_at_patient_createtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='D_hospital',
            field=models.CharField(default='', max_length=15),
        ),
    ]
