# Generated by Django 4.2.11 on 2024-03-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_doctor_d_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
