# Generated by Django 4.2.11 on 2024-03-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_patient_is_cured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='P_hospital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Picture_avatar',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='eyeN_result',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_cured',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_treatment_date',
        ),
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HospitalForTreatment', models.CharField(default='', max_length=15)),
                ('MedicalRecordTime', models.DateTimeField(auto_now_add=True)),
                ('MedicalRecordStatus', models.BooleanField(default=False)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='picture/')),
                ('MedicalRecordResult', models.CharField(default='', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.patient')),
            ],
        ),
    ]
