# Generated by Django 4.2.11 on 2024-03-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_historyrecords_medicalrecordtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyrecords',
            name='MedicalRecordTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='MedicalRecordTime',
            field=models.IntegerField(),
        ),
    ]
