# Generated by Django 4.2.11 on 2024-03-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_historyrecords_medicalrecordtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
