# Generated by Django 4.2.11 on 2024-04-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_patient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
    ]
