# Generated by Django 4.2.11 on 2024-05-15 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_medicalrecords_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyrecords',
            name='PhotoLink',
        ),
        migrations.RemoveField(
            model_name='historyrecords',
            name='Picture',
        ),
        migrations.RemoveField(
            model_name='historyrecords',
            name='Video',
        ),
        migrations.RemoveField(
            model_name='historyrecords',
            name='VideoLink',
        ),
        migrations.RemoveField(
            model_name='medicalrecords',
            name='PhotoLink',
        ),
        migrations.RemoveField(
            model_name='medicalrecords',
            name='Picture',
        ),
        migrations.RemoveField(
            model_name='medicalrecords',
            name='Video',
        ),
        migrations.RemoveField(
            model_name='medicalrecords',
            name='VideoLink',
        ),
        migrations.AddField(
            model_name='historyrecords',
            name='AdviceTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historyrecords',
            name='PictureName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historyrecords',
            name='VideoName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecords',
            name='PictureName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecords',
            name='VideoName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
