# Generated by Django 4.2.11 on 2024-05-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_historyrecords_doctorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
