# Generated by Django 4.2.11 on 2024-05-15 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_doctor_is_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecords',
            name='AdviceTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
