# Generated by Django 4.2.11 on 2024-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_auth_id',
            new_name='hospital_auth_code',
        ),
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
