# Generated by Django 4.2.11 on 2024-03-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_hospital_auth_id_hospital_hospital_auth_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='P_hospital',
            field=models.CharField(default='', max_length=15),
        ),
    ]
