# Generated by Django 4.2.11 on 2024-03-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_patient_p_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_treatment_date',
            field=models.CharField(default=123, max_length=150),
        ),
    ]
