# Generated by Django 4.2.11 on 2024-03-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecords',
            name='MedicalRecordTime',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='HistoryRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HospitalForTreatment', models.CharField(default='', max_length=15)),
                ('MedicalRecordTime', models.IntegerField()),
                ('MedicalRecordStatus', models.BooleanField(default=False)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='picture/')),
                ('MedicalRecordResult', models.CharField(default='', max_length=50)),
                ('DoctorOpinion', models.CharField(max_length=150)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.patient')),
            ],
        ),
    ]
