# Generated by Django 4.2.11 on 2024-03-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_historyrecords_medicalrecordtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyrecords',
            name='MedicalRecordTime',
        ),
        migrations.RemoveField(
            model_name='medicalrecords',
            name='MedicalRecordTime',
        ),
    ]
