# Generated by Django 4.2.11 on 2024-03-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_historyrecords_medicalrecordtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecords',
            name='MedicalRecordTime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalrecords',
            name='MedicalRecordTime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
