# Generated by Django 4.2.11 on 2024-04-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_historyrecords_photolink_historyrecords_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyrecords',
            name='MedicalRecordTime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='MedicalRecordTime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
