# Generated by Django 4.2.11 on 2024-05-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_historyrecords_advicetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecords',
            name='DoctorName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
