# Generated by Django 4.2.16 on 2024-09-17 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0033_historyrecords_advicetime"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.RemoveField(
            model_name="historyrecords",
            name="patient",
        ),
        migrations.DeleteModel(
            name="Hospital",
        ),
        migrations.RemoveField(
            model_name="medicalrecords",
            name="patient",
        ),
        migrations.DeleteModel(
            name="HistoryRecords",
        ),
        migrations.DeleteModel(
            name="MedicalRecords",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
